all:
  hosts:
    odroid1:
      ansible_host: 192.168.1.11  # Replace with your actual IP
      ansible_user: odroid_user1  # Replace with your actual username
    odroid2:
      ansible_host: 192.168.1.12  # Replace with your actual IP
      ansible_user: odroid_user2  # Replace with your actual username
    odroid3:
      ansible_host: 192.168.1.13  # Replace with your actual IP
      ansible_user: odroid_user3  # Replace with your actual username
    odroid4:
      ansible_host: 192.168.1.14  # Replace with your actual IP
      ansible_user: odroid_user4  # Replace with your actual username