version: "3.8"
services:
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    ports:
      - 8080:80
    volumes:
      - ${HEIMDALL_CONFIG}:/config
    restart: unless-stopped
